[server]
address = "127.0.0.1"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#18181B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#09090B"
borderColor = "#E4E4E7"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "8px"
buttonRadius = "6px"
font = "sans-serif"
headingFont = "sans-serif"
baseFontSize = 16
headingFontSizes = ["2.25rem", "1.5rem", "1.25rem", "1rem"]
headingFontWeights = [700, 600, 600, 600]
linkColor = "#18181B"

[theme.sidebar]
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#09090B"
primaryColor = "#18181B"
borderColor = "#E4E4E7"
headingFont = "sans-serif"
